[tool.poetry]
name = "eleicoes_brasil_tse_download"
version = "0.1.0"
description = ""
authors = ["Marcus Braga <mvbraga@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
beautifulsoup4 = "^4.11.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
